name: brik
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # C
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.2.3

  # D
  dio: ^5.4.1
  dartz: ^0.10.1

  # E
  equatable: ^2.0.5

  # F
  flutter_secure_storage: ^9.2.2

  # G
  get_it: ^7.6.7

  # I
  intl: ^0.19.0

  # W
  web_socket_channel: ^2.4.4

  # P
  provider: ^6.1.2

  # R
  readmore: ^2.1.0

  # S
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # fl
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/default/
